### ISSUE TITLE
Strip trailing newlines

### ISSUE THREAD

**Issue by mehturt** [chonton/readfiles-maven-plugin#1]
Is it possible to strip trailing newlines (or even whitespace) from the file read?

**Comment by chonton** [comment]
What is use case? (What problem do you need to solve?)

**Comment by mehturt** [comment]
The file which I read into a property has newline (0x0a) at the end, I need to remove it.  The maven property is then passed into a shell script where newline in the parameter is a problem.

**Comment by chonton** [comment]
Pull requests are welcome. Otherwise, it may be a while before I can get to this.
